#draw a star

import turtle
turtle.speed(1)
turtle.penup()
turtle.goto(-100,45)
turtle.pendown()
#turtle.left(54)
#turtle.right(216)
p1 = turtle.pos()
turtle.write(p1, move=False, align = 'left')
turtle.forward(200)
p1 = turtle.pos()
turtle.write(p1, move=False, align = 'left')
turtle.right(144)
turtle.forward(200)
p1 = turtle.pos()
turtle.write(p1, move=False, align = 'left')
turtle.right(144)
turtle.forward(200)
p1 = turtle.pos()
turtle.write(p1, move=False, align = 'left')
turtle.right(144)
turtle.forward(200)
p1 = turtle.pos()
turtle.write(p1, move=False, align = 'left')
turtle.right(144)
turtle.forward(200)
p1 = turtle.pos()
turtle.write(p1, move=False, align = 'left')
